export const IPC = {
  // invoke 命令
  ProjectsList: 'projects:list',
  ProjectsAdd: 'projects:add',
  ProjectsRemove: 'projects:remove',
  ProjectsRename: 'projects:rename',
  ProjectsRescan: 'projects:rescan',
  ProjectsRelocate: 'projects:relocate',
  ProjectsAddPath: 'projects:addPath',
  ProjectsReorder: 'projects:reorder',
  ProjectsSetPinned: 'projects:setPinned',
  ScriptsStart: 'scripts:start',
  ScriptsStop: 'scripts:stop',
  ScriptsRestart: 'scripts:restart',
  ScriptsPrefs: 'scripts:prefs',
  ScriptsSetPortless: 'scripts:setPortless',
  PortlessAvailable: 'portless:available',
  TerminalWrite: 'terminal:write',
  TerminalResize: 'terminal:resize',
  TerminalGetBuffer: 'terminal:getBuffer',
  ShellOpenExternal: 'shell:openExternal',
  ShellOpenPath: 'shell:openPath',
  EnvRead: 'env:read',
  EnvWrite: 'env:write',
  AppsList: 'apps:list',
  AppsOpenWith: 'apps:openWith',
  PortsWho: 'ports:who',
  PortsKill: 'ports:kill',
  SettingsGet: 'settings:get',
  SettingsSet: 'settings:set',
  DialogPickDirectory: 'dialog:pickDirectory',
  UiGetState: 'ui:getState',
  UiSetState: 'ui:setState',
  SessionsList: 'sessions:list',
  // 事件（main → renderer）
  EvtTerminalData: 'evt:terminal:data',
  EvtSessionStatus: 'evt:session:status',
  EvtSessionUrl: 'evt:session:url',
  EvtProjectUpdated: 'evt:project:updated',
  EvtScriptChanged: 'evt:script:changed',
  EvtEnvChanged: 'evt:env:changed',
  EvtPortConflict: 'evt:port:conflict'
} as const
